### ISSUE TITLE
(spam issue)

### ISSUE THREAD

**Issue by ghost** [brenns10/sos#5]
-

**Comment by brenns10** [comment]
Since you went ahead and deleted your comment:

> Seen this: https://github.com/umanovskis/baremetal-arm/blob/master/src/07_interrupts/src/gic.h
> 
> As well as: https://github.com/brenns10/sos/blob/master/kernel/gic.h
> 
> You can't tell me you didn't copy/paste this dudes data structures and claim you spent "hours" trying to implement this GIC?

Congratulations on proving that you can't even read!

I credit that source at the very top of the `gic.h` file which you linked. It is the register layout of the GIC. Yes, it is copied in: it's very difficult to implement a memory mapped driver without either a struct or list of offsets for the registers. It's also the most mechanical and uninteresting part of the process. Why transcribe from the datasheet when it has already been done? So I did copy it in, and I also credited the author.

And you know what, I probably took a look at their implementations too, so mine probably look similar to theirs. Again, with credit.

It doesn't change that I spent a lot of time myself working on the problem. In fact, because I spent a lot of time banging my head against it, and then found some helpful resource, I made sure to describe that in the comment where I gave credit to the author of that resource!

I don't appreciate your tone coming into my project and acting like this. Unless you have a constructive suggestion (like maybe I should include a copy of their MIT license and copyright statement in the code, rather than relying on that attribution alone) then don't do this sort of thing.

**Comment by ToyOS-project** [comment]
Why do you think I removed my comment? I realized I was wrong.

**Comment by ghost** [comment]
Lmao oh so butthurt. The whole GitHub and OS development platforms are full of butthurt crybaby idiots.
